name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"
      IMAGE_NAME: "my-web-app"
      INSTANCE_USER: "ec2-user"

    steps:
      # 1. Checkout del Código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar Credenciales de AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Build de la Imagen Docker
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      # 4. Login en Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Push de la Imagen Docker
      - name: Push Docker Image
        run: |
          docker tag $IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      # 6. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      # 7. Inicializar Terraform
      - name: Initialize Terraform
        run: terraform init -input=false

      # 8. Validar Configuración
      - name: Terraform Validate
        run: terraform validate

      # 9. Plan de Terraform
      - name: Terraform Plan
        run: terraform plan -var="docker_image=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest"

      # 10. Aplicar Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="docker_image=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest"

      # 11. Depurar la salida de Terraform para la dirección IP del EC2
      - name: Debug EC2 Public IP Output
        run: |
          terraform output -raw web_server_public_ip || true

      # 12. Obtener Dirección Pública del EC2
      # - name: Debug EC2 Public IP
      #   run: echo "Extracted EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}"

      - name: Save EC2 IP to File
        run: |
          RAW_OUTPUT=$(terraform output -raw web_server_public_ip || true)
          CLEANED_IP=$(echo "$RAW_OUTPUT" | tr -d '%\r\n' | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
          
          if [ -z "$CLEANED_IP" ]; then
            echo "Error: Could not extract a valid IP address from Terraform output."
            echo "Terraform Raw Output: $RAW_OUTPUT"
            exit 1
          fi

          echo "$CLEANED_IP" > ec2_ip.txt
          echo "Saved cleaned EC2 IP to ec2_ip.txt: $CLEANED_IP"

      - name: Verify and Export EC2 IP
        run: |
          if [ ! -f ec2_ip.txt ]; then
            echo "Error: ec2_ip.txt not found."
            exit 1
          fi

          RAW_IP=$(head -n 1 ec2_ip.txt | tr -d '\r\n')
          CLEANED_IP=$(echo "$RAW_IP" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')

          if [ -z "$CLEANED_IP" ]; then
            echo "Error: Invalid IP format in ec2_ip.txt."
            echo "Raw IP from file: $RAW_IP"
            exit 1
          fi

          echo "EC2_PUBLIC_IP=$CLEANED_IP" >> $GITHUB_ENV
          echo "Extracted EC2 Public IP: $CLEANED_IP"

      # Read EC2 IP
      - name: Read and Verify EC2 IP
        run: |
          if [ ! -f ec2_ip.txt ]; then
            echo "Error: ec2_ip.txt not found."
            exit 1
          fi
          
          # Leer la dirección IP del archivo
          RAW_IP=$(head -n 1 ec2_ip.txt | tr -d '\r\n')
          
          # Validar que es una dirección IP válida
          CLEANED_IP=$(echo "$RAW_IP" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
          if [ -z "$CLEANED_IP" ]; then
            echo "Error: Invalid IP format in ec2_ip.txt."
            echo "Raw IP from file: $RAW_IP"
            exit 1
          fi
          
          # Exportar la dirección IP como variable de entorno
          echo "EC2_PUBLIC_IP=$CLEANED_IP" >> $GITHUB_ENV
          echo "Extracted EC2 Public IP: $CLEANED_IP"

      - name: Debug GITHUB_ENV
        run: cat $GITHUB_ENV

      # - name: Get EC2 Public IP
      #   id: get_ec2_ip
      #   run: |
      #     RAW_OUTPUT=$(terraform output -raw web_server_public_ip || true)
      #     EC2_PUBLIC_IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
      #     if [ -z "$EC2_PUBLIC_IP" ]; then
      #       echo "Error: Could not extract a valid IP address."
      #       exit 1
      #     fi
      #     echo "Extracted EC2 Public IP: $EC2_PUBLIC_IP"
      #     echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV

      # # 13. Depurar Dirección Pública del EC2 Exportada
      # - name: Debug EC2 Public IP
      #   run: echo "Extracted EC2_PUBLIC_IP: ${{ steps.get_ec2_ip.outputs.public_ip }}"

      # 14. Configurar EC2 y Desplegar el Contenedor
      - name: Configure EC2 and Deploy Container
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $INSTANCE_USER@${{ env.EC2_PUBLIC_IP }} "
            sudo docker stop \$(sudo docker ps -q) || true &&
            sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          "
