name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"
      IMAGE_NAME: "my-web-app"
      INSTANCE_USER: "ec2-user"
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      # 1. Checkout del Código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar Credenciales de AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Build de la Imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # 4. Login en Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Push de la Imagen Docker
      - name: Push Docker Image
        run: |
          docker tag $IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      # 6. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      # 7. Inicializar Terraform
      - name: Initialize Terraform
        run: terraform init -input=false

      # 8. Validar Configuración
      - name: Terraform Validate
        run: terraform validate

      # 9. Plan de Terraform
      - name: Terraform Plan
        run: terraform plan -var="docker_image=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest"

      # 10. Aplicar Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="docker_image=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest"

      # 11. Obtener Dirección Pública del EC2
      - name: Get EC2 Public IP
        id: get_ec2_ip
        run: |
          EC2_PUBLIC_IP=$(terraform output -raw web_server_public_ip | tr -d '\r')
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP"
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV

      # 12. Configurar EC2 y Desplegar el Contenedor
      - name: Configure EC2 and Deploy Container
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $INSTANCE_USER@$EC2_PUBLIC_IP "
            sudo docker stop \$(sudo docker ps -q) || true &&
            sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          "